### ISSUE TITLE
Default behavior on VPN drop?

### ISSUE THREAD

**Issue by whophil** [jbogatay/docker-piavpn#3]
What is the default behavior for internet traffic if the VPN drops? Does it disconnect entirely (kill switch), or does it route through regular eth0?

If there is no kill switch functionality currently incorporated I'd be interested in contributing. Feel free to send me an e-mail to discuss (address in my profile).

**Comment by nbonfire** [comment]
As far as I can tell there's no kill switch. I tested by putting an invalid username and password for PIA and deluge still starts. Using a torrent from ipleak.net showed my home IP address. 

I think just a default policy of dropping all packets before building the routing table should be enough for this to kill connections when not connected.

**Comment by jbogatay** [comment]
Deluge would still start on a fresh container probably yeah.   After it's
run once successfully, the listening interface is bound to an IP address
from tun, so subsequent vpn failures should not leak anything.

You could add a check for the tun device being up and running prior to
starting the deluge daemon.   Or force the deluge service to fail unless
tun0 has a valid IP.

I have actually moved away from docker for this.    I'm using nspawn and
loving it.

**Comment by nbonfire** [comment]
Thanks.

**Comment by danpolanco** [comment]
Should we close this issue?

**Comment by nbonfire** [comment]
I'm using this container on a regular basis, and it does have a kill switch. I think we can close this issue, but it might be a good idea to mention in the readme that on first boot deluge will start regardless of vpn.

**Comment by jbogatay** [comment]
Closing.   Although it looks like Dan's fork is even more secure.....

**Comment by danpolanco** [comment]
I wish. It was spitting all sorts of errors. If I get it to work properly, I'll send a pull request.
