### ISSUE TITLE
It's not clear how to find the deluge logfile

### ISSUE THREAD

**Issue by nbonfire** [jbogatay/docker-piavpn#5]
Hi, your container is great. However It's not clear how I should view the deluge logfile. There's no logfile specified when you start deluged, so I think that means it goes to the console. If I try to attach to my running container i don't see messages (although that could be a problem with my setup and not your scripts). I recommend setting a logfile location in the deluge config folder, or an option for one.

**Comment by jbogatay** [comment]
Have you tried docker logs <containername>?    

I have moved on to using nspawn personally.
