### ISSUE TITLE
Port Forwarding not available in all areas

### ISSUE THREAD

**Issue by kiowadriver** [jbogatay/docker-piavpn#7]
I found an issue with the set_deluge_port script:

Apparently port forwarding is not allowed in all regions.  I am attempting to use the California PIA gateway and it is not allowed there causing the script to fail because the PORT will be an error string and not an integer value.

I would like to suggest a change to the logic to skip assigning a port forward if this error is returned since it is not necessary for operation.  I would also like to suggest removing 'deluge-web' all together and just forwarding the deluged port of 58846 to the host.  It is easier to run deluge-web on the host so you can access it outside of your LAN.

PORT=`curl -s -d "user=$USERNAME&pass=$PASSWORD&client_id=$CLIENTID&local_ip=$LOCAL_IP" https://www.privateinternetaccess.com/vpninfo/port_forward_assignment | head -1 | grep -Po "[0-9]*"`

**Comment by jbogatay** [comment]
The original intent was a 'all-in-one' container for torrenting and browsing over PIA.   That requires a PIA endpoint that supports port forwarding.   The port forwarding is required for seeding.  Feel free to fork and create a lightweight version.    I have moved on from PIA at the moment.....
